---
- name: Install Ansible
  hosts: ansible
  become: yes

  tasks:
    - name: Install Python (required for Ansible)
      raw: yum install -y python3

    - name: Install Ansible
      raw: pip3 install ansible

    - name: installing the git 
      yum: 
       name: git 
       state: present 