---
- name: Install Ansible on target CentOS servers
  hosts: ansible   # Replace with your actual target server group
  become: yes  # Elevate privileges for package installation

  tasks:
    - name: Ensure EPEL repository is installed
      yum:
        name: epel-release
        state: present

    - name: Install Ansible package
      yum:
        name: ansible
        state: latest
