---
- name: Install Ansible
  hosts: ansible  # Replace with the specific hosts or groups you want to target
  become: yes  # Elevate privileges to install packages

  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python3-pip
          - python3-setuptools
          - libffi-dev

    - name: Install Ansible via pip
      pip:
        name: ansible
        executable: pip3
