- name: installing the ansible and git
  hosts: ansible 
  become: yes
  tasks:
  - name: installing the ansible 
    ansible.builtin.yum:
      name: ansible 
      state: installed
  - name: installing the git 
    ansible.builtin.yum: 
      name: git 
      state: present 